services:
  postgres:
    image: postgres:15-alpine
    container_name: nest-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: costumes
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: nest-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - app-network
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: nest-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/crm-frontend/Dockerfile
    container_name: crm-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
  redis_data:
  redis_insight_data:
